### ISSUE TITLE
No task/cmd for creating a new bot

### ISSUE THREAD

**Issue by mculp** [thorncp/rubot#34]
The `-i` flag existed in version 0.2 but it's not there anymore. The readme says `rubot new botname` but that also does not exist.

**Comment by thorncp** [comment]
Yeah, this was one of the reasons holding up a new release. At present, the only command supported is `server`, anything else will just [be ignored](https://github.com/thorncp/rubot/blob/cd67772110025e22ad41f6e783b7f0b101edda1f/bin/rubot#L27).

Related to #33

**Comment by mculp** [comment]
What all needs to be done by the 'new' command? Create the directory structure?

**Comment by thorncp** [comment]
Directory structure, a config file with sane defaults, and maybe example controller/resource. Can't think of anything else at the moment.

**Comment by mculp** [comment]
k, I'll try and get this one done soon
